name: Get and Cache Dependencies
description: |
  This action checks out the code and caches the node modules to speed up subsequent runs.
inputs:
  caching:
    description: Whether to cache node modules
    required: false
    default: true
    type: boolean
outputs:
  used-cache:
    description: Whether the cache was used
    value: ${{ steps.install-deps.outputs.cache }}
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      id: install-deps
      if: steps.cache-node-modules.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache=${{ inputs.caching }}" >> $GITHUB_OUTPUT
      shell: bash
