name: Get and Cache Dependencies
description: |
  This action checks out the code and caches the node modules to speed up subsequent runs.
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        npm ci
      shell: bash
